version: "3"
services:
  db:
    image: "postgres:11"
    environment:
      POSTGRES_USER: source
      POSTGRES_PASSWORD: secret
    container_name: "pgdb"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: