version: "3"
services:
  db:
    image: "postgres:11"
    environment:
      POSTGRES_USER: source
      POSTGRES_PASSWORD: secret
    container_name: "db"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
  user_api:
    image: "andreyshtamburg/learning_source:ls_user_api"
    container_name: "ls_user_api"
    ports:
      - "5533:5533"
    environment:
      POSTGRES_DB: source
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: source
    depends_on:
      - db
  ls_api:
    image: "andreyshtamburg/learning_source:ls_source_api"
    container_name: "ls_source_api"
    ports:
      - "4433:4433"
    environment:
      POSTGRES_DB: source
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: source
    depends_on:
      - user_api
volumes:
  my_dbdata: